import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, MessageCircle, Sprout, Truck, Users, Phone, Mail, MapPin, BadgeTurkishLira } from 'lucide-react';
import s from './site.module.css';
export { s };
export const whatsapp='https://wa.me/905334928522';
export function WhatsApp({children='WhatsApp’tan fiyat al'}:{children?:React.ReactNode}){return <a className={s.button} href={whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/>{children}<ArrowUpRight size={17}/></a>}
export function Photo({src,alt,priority=false}:{src:string;alt:string;priority?:boolean}){return <Image src={src} alt={alt} fill sizes="(max-width: 760px) 100vw, 60vw" preload={priority} className={s.photo}/>}
export function Shell({children}:{children:React.ReactNode}){return <div className={s.site}><a className={s.skip} href="#icerik">İçeriğe geç</a><header className={s.header}><div className={s.headerInner}><Link href="/" aria-label="Niba Tarım ana sayfa"><Image src="/niba-logo-horizontal.png" alt="Niba Tarım" width={150} height={80} className={s.logo}/></Link><nav className={s.desktopNav} aria-label="Ana menü"><Link href="/hakkimizda">Hakkımızda</Link><Link href="/urunler">Ürünler</Link><Link href="/markalar">Markalar</Link><Link href="/blog">Blog</Link><Link href="/iletisim">İletişim</Link></nav><div className={s.headerActions}><a className={s.smallButton} href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp <ArrowUpRight size={15}/></a></div><details className={s.mobileMenu}><summary>Menü</summary><nav aria-label="Mobil menü"><Link href="/">Ana sayfa</Link><Link href="/hakkimizda">Hakkımızda</Link><Link href="/urunler">Ürünler</Link><Link href="/markalar">Markalar</Link><Link href="/blog">Blog</Link><Link href="/iletisim">İletişim</Link></nav></details></div></header><main id="icerik">{children}</main><footer className={s.footer}><div className={s.container}><div className={s.footerGrid}><div><Image src="/niba-logo-horizontal.png" alt="Niba Tarım" width={140} height={80} className={s.logo}/><p>Toprağın gücüne,<br/>işinizin geleceğine.</p></div><nav aria-label="Alt menü"><Link href="/hakkimizda">Hakkımızda</Link><Link href="/urunler">Ürünler</Link><Link href="/markalar">Markalar</Link><Link href="/blog">Tarım rehberi</Link></nav><address><a href="tel:+905334928522"><Phone size={16}/>0533 492 85 22</a><a href="mailto:info@nibatarim.com"><Mail size={16}/>info@nibatarim.com</a><span><MapPin size={16}/>Esentepe Mah. Büyükdere Cad. No: 199/-6, Şişli / İstanbul</span></address></div><div className={s.copyright}>© {new Date().getFullYear()} Niba Tarım. Tüm hakları saklıdır.<Link href="/iletisim">İletişime geçin ↗</Link></div></div></footer></div>}
export function Intro({label,title,text}:{label:string;title:string;text:string}){return <section className={s.intro}><div className={s.container}><div className={s.breadcrumb}><Link href="/">Niba Tarım</Link><span>/</span>{label}</div><span className={s.eyebrow}>{label}</span><h1>{title}</h1><p>{text}</p></div></section>}
export const products=[{slug:'gubre',title:'Gübre Grubu',image:'/site/fertilizer-urea-bags.jpg',text:'CAN 26, üre, DAP ve kompoze gübre çeşitlerinde tedarik desteği.'},{slug:'yem',title:'Yem Grubu',image:'/site/feed-product.jpg',text:'Hayvancılık işletmeleri ve bayiler için yem grubu ürünlerinin tedariği.'},{slug:'tarimsal-urunler',title:'Tarımsal Ürünler',image:'/site/sunflower-field.jpg',text:'Tarımsal işletmelerin ihtiyaçlarına uygun ürün ve tedarik çözümleri.'}];
export function Products(){return <div className={s.cards}>{products.map(p=><Link className={s.card} href={'/urunler#'+p.slug} key={p.slug}><div className={s.cardImage}><Photo src={p.image} alt={p.title}/></div><div className={s.cardBody}><h3>{p.title}</h3><p className={s.productSummary}>{p.text}</p><span>Ürünleri inceleyin <ArrowUpRight size={17}/></span></div></Link>)}</div>}
export function Benefits(){return <div className={s.benefits}>{[{Icon:BadgeTurkishLira,title:'Uygun fiyat',text:'İhtiyacınıza uygun, rekabetçi teklifler'},{Icon:Sprout,title:'Ürün tedariği',text:'İhtiyacınıza uygun ürün seçenekleri'},{Icon:Truck,title:'Sevkiyat koordinasyonu',text:'Miktar ve teslimat planlaması'},{Icon:Users,title:'Bayi iletişimi',text:'Tekliften teslimata iletişim'}].map(({Icon,title,text})=><div key={title}><Icon size={32}/><div><h3>{title}</h3><p>{text}</p></div></div>)}</div>}
export function Brands(){return <div className={s.brands}>{['vitamin','bagfas','eti-bakir','igsas'].map((b,i)=><div key={b}><Image src={'/brands/'+b+'.png'} alt={['Vitamin Gübre Tarım A.Ş.','Bagfaş','Eti Bakır','İGSAŞ'][i]} width={180} height={80}/></div>)}</div>}
export const posts=[{slug:'toptan-gubre-bayiler-icin-tedarik-rehberi',title:'Toptan gübre ve gübre fiyatları',description:'Tarım bayileri için 50 kg çuval, bigbag, ton fiyatı ve teslimat rehberi.',image:'/site/fertilizer-urea-bags.jpg',tag:'Bayi tedarik rehberi'},{slug:'gubre-fiyatlari',title:'Gübre fiyatlarını etkileyen faktörler',description:'Ürün, miktar ve teslimat koşullarına göre teklif sürecini keşfedin.',image:'/site/wheat-landscape.jpg',tag:'Gübre rehberi'},{slug:'can-26-gubre-fiyati',title:'CAN 26 gübre ve tedarik rehberi',description:'CAN 26 ürün grubunu ve fiyat teklifinde ihtiyaç duyulan bilgileri tanıyın.',image:'/site/canola-field.jpg',tag:'Ürün rehberi'}];
export function Posts(){return <div className={s.postGrid}>{posts.map(p=><Link className={s.card} href={'/blog/'+p.slug} key={p.slug}><div className={s.cardImage}><Photo src={p.image} alt={p.title}/></div><div className={s.cardBody}><span className={s.eyebrow}>{p.tag}</span><h3>{p.title}</h3><p>{p.description}</p><span>Yazıyı okuyun <ArrowUpRight size={17}/></span></div></Link>)}</div>}
