"use client";
import { useEffect, useId, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Banknote, ClipboardList, Minus, RefreshCw, Scale } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { SalesSummary } from '@/lib/orders/sales-summary';
import styles from './sales-overview.module.css';
function Sparkline({values,color,label}:{values:number[];color:string;label:string}) {
  const id=useId().replace(/:/g,'');const high=Math.max(...values,1);const points=values.map((value,index)=>`${8+(values.length>1?index/(values.length-1):.5)*224},${55-value/high*43}`).join(' ');
  return <svg className={styles.sparkline} viewBox="0 0 240 66" role="img" aria-label={label} preserveAspectRatio="none"><defs><linearGradient id={id} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity=".13"/><stop offset="100%" stopColor={color} stopOpacity=".02"/></linearGradient></defs>{values.length>1 && <><polygon points={`8,66 ${points} 232,66`} fill={`url(#${id})`}/><polyline points={points} fill="none" stroke={color} strokeWidth="1.5" strokeLinejoin="round" strokeLinecap="round" vectorEffect="non-scaling-stroke"/></>}{values.length===1 && <circle cx="120" cy={55-values[0]/high*43} r="3" fill={color}/>}</svg>;
}
export default function SalesOverview() {
  const [data,setData]=useState<SalesSummary|null>(null),[period,setPeriod]=useState('day'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  useEffect(()=>{
    const controller=new AbortController();
    async function load(){setLoading(true);setError('');try{const {data:auth}=await supabase.auth.getSession();if(!auth.session)throw new Error('Oturum açman gerekiyor.');const response=await fetch('/api/admin/sales-summary',{headers:{Authorization:`Bearer ${auth.session.access_token}`},cache:'no-store',signal:controller.signal});const result=await response.json();if(!response.ok || !result.success)throw new Error(result.error || 'Satış özeti alınamadı.');if(!controller.signal.aborted)setData(result);}catch(cause){if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'Satış özeti alınamadı.');}finally{if(!controller.signal.aborted)setLoading(false);}}
    void load();return()=>controller.abort();
  },[refresh]);
  const selected=data?.periods.find(p=>p.key===period);
  const format=(n:number,digits=0)=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:digits}).format(n);
  const cards=[{key:'tons' as const,title:'Teslim edilen tonaj',unit:'ton',icon:Scale,color:'#19a896',digits:3},{key:'count' as const,title:'Satış adedi',unit:'sipariş',icon:ClipboardList,color:'#5b97d5',digits:0},{key:'amount' as const,title:'Toplam satış tutarı',unit:'₺',icon:Banknote,color:'#ba9957',digits:2}];
  return <section className={styles.section} aria-labelledby="sales-overview-title" aria-busy={loading}>
    <header className={styles.header}><div><h2 id="sales-overview-title">Satış özeti</h2><p>{selected?.range || 'Günlük, aylık ve yıllık satışlarını takip et.'}</p></div><div className={styles.actions}><div className={styles.tabs} aria-label="Satış dönemi">{[{key:'day',label:'Günlük'},{key:'month',label:'Aylık'},{key:'year',label:'Yıllık'}].map(item=><button key={item.key} type="button" aria-pressed={period===item.key} onClick={()=>setPeriod(item.key)}>{item.label}</button>)}</div><button type="button" className={styles.refresh} onClick={()=>setRefresh(n=>n+1)} disabled={loading} aria-label="Satış özetini yenile"><RefreshCw size={15} className={loading ? styles.spinning : ''}/></button></div></header>
    {error && <p className={styles.error} role="alert">{error} {data ? 'Son alınan özet gösteriliyor.' : ''}<button type="button" onClick={()=>setRefresh(n=>n+1)} disabled={loading}>Yeniden dene</button></p>}
    <div className={styles.cards}>{cards.map(card=>{const metric=selected?.[card.key];const change=metric?.change;const positive=typeof change==='number' && change>0,negative=typeof change==='number' && change<0;const Icon=positive?ArrowUpRight:negative?ArrowDownRight:Minus;return <article key={card.key} className={styles.card}><div className={styles.cardContent}><div className={styles.label}><span>{card.title}</span><card.icon size={17} style={{color:card.color}}/></div><p className={styles.value}>{metric ? <>{card.key==='amount' && <small>₺</small>}{format(metric.value,card.digits)}{card.key!=='amount' && <small>{card.unit}</small>}</> : '—'}</p><div className={styles.comparison}>{metric && change != null ? <><span className={`${styles.change} ${positive ? styles.up : negative ? styles.down : styles.flat}`}><Icon size={13}/>{positive ? '+' : negative ? '−' : ''}%{format(Math.abs(change),1)}</span><span>{selected?.comparison}</span></> : <span className={styles.unavailable}>{!metric ? loading ? 'Özet hazırlanıyor…' : 'Veri alınamadı' : selected?.previousRecords===0 ? 'Önceki dönem kaydı yok' : metric.missingPrice ? 'Fiyatı eksik kayıtlar var' : 'Önceki dönem değeri sıfır'}</span>}</div>{card.key==='amount' && !!selected?.missingPrices && <p className={styles.warning}>{selected.missingPrices} siparişin satış fiyatı eksik; tutar tamamlanmadı.</p>}</div>{metric && <Sparkline values={metric.series} color={card.color} label={`${period==='year'?'Aylara':'Günlere'} göre ${card.title.toLocaleLowerCase('tr-TR')} grafiği`}/>}</article>;})}</div>
    <p className={styles.note}>Satış tarihi esas alınır · Tonaj ve tutar teslim edilen miktara göre hesaplanır · İptal edilen siparişler hariç{data?.ignored ? ` · ${data.ignored} tarihsiz veya geçersiz kayıt hariç` : ''}</p>
  </section>;
}
