const {test}=require('node:test'); const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../app/api/admin/parasut/sales-invoice/create-from-order/route.ts'),'utf8');
const fn=source.slice(source.indexOf('function buildSalesInvoicePayload('),source.indexOf('async function createEInvoice'));
const ctx={clean:v=>String(v??'').trim(),toNumber:v=>Number(v||0),today:()=> '2026-10-07'};vm.createContext(ctx);vm.runInContext(ts.transpile(fn),ctx);
function build(allocated=4000,vat=0) {return ctx.buildSalesInvoicePayload({customerId:'test',order:{id:'test',siparisTonaj:2,pesinSatisFiyati:2500,bayiSatisToplam:5000,matched_purchase_allocated_amount:allocated},purchaseBill:{data:{attributes:{currency:'TRL',net_total:10000}},included:[{type:'purchase_bill_details',attributes:{description:'Gübre',quantity:2000,unit:'kg',unit_price:5,net_total:10000,vat_rate:vat}}]}})}
test('shared bill uses allocated quantity and preserves zero VAT with order selling total',()=>{const result=build();assert.equal(result.preview.details[0].quantity,800);assert.equal(result.preview.details[0].vat_rate,0);assert.equal(result.preview.vatTotal,0);assert.equal(result.preview.estimatedTotal,5000);assert.equal(result.preview.sourceShare,.4)});
test('VAT is included in selling total and original rate is preserved',()=>{const result=build(4000,20);assert.equal(result.preview.details[0].vat_rate,20);assert.equal(result.preview.estimatedTotal,5000)});
test('invalid allocation blocks invoice creation',()=>{assert.throws(()=>build(0),/ayrılan/);assert.throws(()=>build(12000),/ayrılan/)});
test('reusable list omits exhausted bills and totals multiple allocations',async()=>{
 const pool=[{e_invoice_id:'a',purchase_bill_id:'a',total:100000},{e_invoice_id:'b',purchase_bill_id:'b',total:100000}];const orders=[{matched_purchase_invoice_id:'a',matched_purchase_allocated_amount:40000},{matched_purchase_invoice_id:'a',matched_purchase_allocated_amount:20000},{matched_purchase_invoice_id:'b',matched_purchase_allocated_amount:100000}];
 const db={from:table=>{const q={select:()=>q,eq:()=>q,order:async()=>({data:pool}),in:()=>q,range:async()=>({data:orders})};return q}};
 const module={exports:{}};const code=ts.transpile(fs.readFileSync(path.join(__dirname,'../lib/parasut/invoice-pool.ts'),'utf8'),{module:ts.ModuleKind.CommonJS});const sandbox={module,exports:module.exports,require:()=>({createClient:()=>db}),process:{env:{}}};vm.createContext(sandbox);vm.runInContext(code,sandbox);const result=await sandbox.exports.reusableInvoices();assert.equal(result.length,1);assert.equal(result[0].allocated_amount,60000);assert.equal(result[0].remaining_amount,40000);
});
