const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ts=require('typescript');const root=path.resolve(__dirname,'..');
function load(file,mocks={},env={}){const exports={};const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,require:n=>n in mocks?mocks[n]:require(n),process:{env},Response,Request});return exports;}
const workflow=load('lib/orders/workflow.ts'),dispatch=load('lib/orders/dispatch.ts');
test('partial dispatch and missing plate stay in dispatch work queue',()=>{assert.equal(workflow.orderStage({sevkDurumu:'Kısmi Sevk',plaka:'33 DEM 123'}),'sevk');assert.equal(workflow.orderStage({sevkDurumu:'Sevk Edildi'}),'sevk');assert.equal(workflow.orderStage({sevkDurumu:'Sevk Edildi',plaka:'33 DEM 123'}),'fatura');});
test('existing invoices and cancelled orders do not become invoice tasks',()=>{assert.equal(workflow.orderStage({sales_invoice_id:'invoice'}),'done');assert.equal(workflow.orderStage({sales_invoice_no:'INV-1'}),'done');assert.equal(workflow.orderStage({sevkDurumu:'İptal'}),'cancelled');});
test('dispatch update rejects accounting fields and invalid tonnage',()=>{for(const fields of [{sales_invoice_id:'evil'},{matched_purchase_invoice_no:'evil'},{teslimOlanTonaj:-2},{teslimOlanTonaj:'NaN'},{teslimOlanTonaj:null},{}])assert.throws(()=>dispatch.dispatchPatch(fields));});
function route({user={email:'admin@example.test'},error=null,env={},result={data:{id:'order-1',sales_invoice_id:'unchanged'},error:null}}={}){const calls=[];const client={auth:{getUser:async()=>({data:{user},error})},from:table=>{const call={table};calls.push(call);const q={update:patch=>{call.patch=patch;return q},eq:(key,value)=>{call.filter=[key,value];return q},select:()=>q,single:async()=>result};return q}};return {calls,handler:load('app/api/admin/siparisler/update-field/route.ts',{'@supabase/supabase-js':{createClient:()=>client},'@/lib/orders/dispatch':dispatch,'next/server':{NextResponse:{json:Response.json}}},env).POST};}
function request(body,token=true){return new Request('http://localhost/api/admin/siparisler/update-field',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer local-test'}:{})},body:JSON.stringify(body)});}
test('one atomic update saves dispatch fields without modifying Paraşüt references',async()=>{const r=route();const fields={plaka:'33 DEM 123',sevkYeri:'Mersin',sevkNo:'SEVK-1',teslimOlanTonaj:27,sevkDurumu:'Sevk Edildi',gts:'Girildi'};const response=await r.handler(request({id:'order-1',fields}));assert.equal(response.status,200);assert.equal(r.calls.length,1);assert.deepEqual(JSON.parse(JSON.stringify(r.calls[0])),{table:'siparisler',patch:fields,filter:['id','order-1']});assert.equal((await response.json()).row.sales_invoice_id,'unchanged');});
test('legacy single-field request remains compatible for signed-in users',async()=>{const r=route();assert.equal((await r.handler(request({id:'order-1',field:'plaka',value:'33 DEM 123'}))).status,200);assert.equal(r.calls[0].patch.plaka,'33 DEM 123');});
test('missing session, invalid session, anonymous and non-allowlisted users cannot write',async()=>{for(const [options,token,status] of [[{},false,401],[{error:{message:'invalid'}},true,401],[{user:{is_anonymous:true}},true,401],[{env:{ADMIN_EMAILS:'owner@example.test'}},true,403]]){const r=route(options);assert.equal((await r.handler(request({id:'order-1',fields:{plaka:'X'}},token))).status,status);assert.equal(r.calls.length,0);}});
test('malformed request never writes; database errors are reported without success',async()=>{const r=route();assert.equal((await r.handler(request({id:'order-1',fields:{sales_invoice_id:'X'}}))).status,400);assert.equal(r.calls.length,0);const failing=route({result:{data:null,error:{message:'Database unavailable'}}});const response=await failing.handler(request({id:'order-1',fields:{plaka:'X'}}));assert.equal(response.status,500);assert.equal((await response.json()).success,false);});
