const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file){const module={exports:{}};const ctx={module,exports:module.exports};vm.createContext(ctx);vm.runInContext(ts.transpile(fs.readFileSync(file,'utf8'),{module:ts.ModuleKind.CommonJS}),ctx);return module.exports;}
const {refundPayload,refundSourceLines,upstreamRefundError,priceDifferenceEDocument}=load('lib/parasut/purchase-refund.ts');const {purchaseAllocation}=load('lib/orders/sales-progress.ts');
const line={id:'line',name:'Gübre',vatRate:0,exemptionCode:'351'};
test('accepted ±50 differences consume actual invoice',()=>{for(const value of [950,1050])assert.equal(purchaseAllocation({purchase_difference_mode:'accept',matched_purchase_allocated_amount:value,teslimOlanTonaj:1,alisFiyati:1000}),value);});
test('detailed refund uses Fiyat farkı service, selected source VAT and exact exemption',()=>{const result=refundPayload({id:'sale',purchase_difference_amount:1350},{supplier_id:'supplier',purchase_bill_id:'source',invoice_no:'INV'},line,'service','2026-10-09').data;assert.match(result.attributes.description,/INV numaralı faturaya istinaden/);assert.match(result.attributes.invoice_note,/INV numaralı faturaya istinaden/);assert.equal(result.attributes.net_total,1350);assert.equal(result.attributes.total_vat,0);assert.match(result.attributes.description,/İstisna|istisna kodu: 351/);const detail=result.relationships.details.data[0];assert.equal(detail.attributes.description,'Fiyat farkı');assert.equal(detail.attributes.quantity,1);assert.equal(detail.attributes.unit_price,1350);assert.equal(detail.attributes.vat_rate,0);assert.equal(detail.relationships.product.data.id,'service');const taxable=refundPayload({id:'sale',purchase_difference_amount:50},{supplier_id:'supplier'},{...line,vatRate:20,exemptionCode:null},'service','2026-10-09').data;assert.equal(taxable.attributes.total_vat,8.33);assert.equal(taxable.relationships.details.data[0].attributes.vat_rate,20);assert.ok(Math.abs(taxable.relationships.details.data[0].attributes.unit_price*1.2-50)<.000001);});
test('source exemption is copied without replacing 351 with 326; missing exemption blocks zero VAT',()=>{const document={included:[{id:'line',type:'purchase_bill_details',attributes:{vat_rate:0,description:'Gübre'}}]};const incoming={data:{attributes:{vat_exemption_reason_code:'351'}}};assert.equal(refundSourceLines(document,incoming)[0].exemptionCode,'351');assert.throws(()=>refundSourceLines(document,{}),/istisna kodu/);assert.throws(()=>refundPayload({purchase_difference_amount:50},{},{...line,exemptionCode:null},'service','date'));document.included[0].attributes.vat_exemption_reason_code='326';assert.equal(refundSourceLines(document,incoming)[0].exemptionCode,'326');});
function route({reserveError=null,confirm=true,sourceSupplier='supplier',state='pending',refundId=null,rejected=false,wrongCreatedTotal=false,code='351'}={}){const calls=[],updates=[];const order={id:'sale',purchase_difference_mode:'refund',purchase_difference_amount:50,purchase_difference_expected:1000,matched_purchase_invoice_id:'source',purchase_refund_state:state,purchase_refund_id:refundId};const bill={e_invoice_id:'einvoice',purchase_bill_id:'source',supplier_id:'supplier',total:1050,state:'ready'};
 const db={from:table=>{const query={select:()=>query,eq:()=>query,single:async()=>({data:table==='siparisler'?order:bill}),update:patch=>{updates.push(patch);const q={eq:()=>q,then:resolve=>resolve({error:null})};return q}};return query},rpc:async(name,args)=>{assert.deepEqual(Object.keys(args).sort(),['p_amount','p_order_id']);return{error:reserveError}}};const mod={exports:{}};
 const ctx={module:mod,exports:mod.exports,Request,URLSearchParams,Intl,Date,process:{env:{PARASUT_COMPANY_ID:'company'}},require:name=>name.includes('purchase-refund')?{refundPayload,refundSourceLines,upstreamRefundError,priceDifferenceEDocument}:name.includes('invoice-pool')?{invoiceAdmin:()=>db}:name.includes('whatsapp')?{authorizeWhatsApp:async()=>null}:{NextResponse:{json:(data,init)=>({data,status:init?.status||200})}},fetch:async(url,options)=>{calls.push([url,options]);if(url.includes('oauth'))return{ok:true,json:async()=>({access_token:'demo'})};if(url.includes('/e_invoices/'))return{ok:true,json:async()=>({data:{id:'einvoice',attributes:{vat_exemption_reason_code:code}}})};if(url.includes('/products'))return{ok:true,json:async()=>({data:[{id:'service',attributes:{name:'Fiyat farkı',inventory_tracking:false}}]})};if(options?.method==='POST')return rejected?{ok:false,status:422,json:async()=>({errors:[{detail:'Kalem zorunlu'}]})}:{ok:true,json:async()=>({data:{id:'refund'}})};return{ok:true,json:async()=>({data:{attributes:{net_total:url.includes('/refund?')?(wrongCreatedTotal?51:50):1050,total_vat:0,item_type:url.includes('/refund?')?'invoice':'purchase_bill'},relationships:{supplier:{data:{id:sourceSupplier}},contact:{data:{id:sourceSupplier}}}},included:[{id:'line',type:'purchase_bill_details',attributes:{vat_rate:0,description:'Gübre'}}]})}}};vm.createContext(ctx);vm.runInContext(ts.transpile(fs.readFileSync('app/api/admin/parasut/purchase-refund/route.ts','utf8'),{module:ts.ModuleKind.CommonJS}),ctx);return{calls,updates,post:()=>mod.exports.POST({json:async()=>({orderId:'sale',amount:50,sourceLineId:'line',vatRate:0,exemptionCode:'351',returnType:'price',confirm})})};}
test('handler verifies refund; duplicate attempts cannot create a second record',async()=>{const f=route();assert.equal((await f.post()).data.success,true);assert.equal(f.calls.filter(([url,o])=>url.includes('/sales_invoices')&&o.method==='POST').length,1);const duplicate=route({reserveError:{message:'Önceki iade işlemi'}});assert.equal((await duplicate.post()).status,409);assert.equal(duplicate.calls.some(([url,o])=>url.includes('sales_invoices')&&o.method==='POST'),false);});
test('rejected create resets only creating state to pending and exposes exact upstream error',async()=>{const f=route({rejected:true});const response=await f.post();assert.equal(response.data.error,'Kalem zorunlu');assert.equal(f.updates[0].purchase_refund_state,'pending');});
test('confirmation, exact tax code and source identity required before external creation',async()=>{for(const options of [{confirm:false},{sourceSupplier:'wrong'},{state:'created',refundId:'refund'},{code:'326'},{wrongCreatedTotal:true}])assert.equal((await route(options).post()).status,409);});

test('product return preserves product ID, unit price, VAT and quantity; price difference always quantity 1',()=>{const product={...line,productId:'original',unit:'kg',unitPrice:25,availableQuantity:27000,discountRate:0};const data=refundPayload({purchase_difference_amount:1350},{supplier_id:'supplier'},product,'original','2026-10-09','product',54).data;const detail=data.relationships.details.data[0];assert.equal(data.type,'sales_invoices');assert.equal(data.attributes.item_type,'invoice');assert.equal(data.relationships.contact.data.id,'supplier');assert.equal(detail.type,'sales_invoice_details');assert.equal(detail.attributes.description,'Gübre');assert.equal(detail.attributes.quantity,54);assert.equal(detail.attributes.unit_price,25);assert.equal(detail.attributes.vat_rate,0);assert.equal(detail.relationships.product.data.id,'original');assert.throws(()=>refundPayload({purchase_difference_amount:1350},{},product,'original','date','product',55),/uyuşmuyor/);const price=refundPayload({purchase_difference_amount:1350},{},product,'service','date','price',54);assert.equal(price.data.relationships.details.data[0].attributes.quantity,1);});
test('e-Fatura payload uses the original exemption code with sales invoice direction',()=>{const d=priceDifferenceEDocument('sales','inbox',line).data;assert.equal(d.attributes.vat_exemption_reason_code,'351');assert.equal(d.relationships.invoice.data.type,'sales_invoices');assert.equal(d.relationships.invoice.data.id,'sales');});
