const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file){const module={exports:{}};const ctx={module,exports:module.exports};vm.createContext(ctx);vm.runInContext(ts.transpile(fs.readFileSync(file,'utf8'),{module:ts.ModuleKind.CommonJS}),ctx);return module.exports;}
const {refundPayload,refundVatRates}=load('lib/parasut/purchase-refund.ts');
const {purchaseAllocation}=load('lib/orders/sales-progress.ts');
test('accepted ±50 differences consume the actual invoice and preserve delivered sale amounts',()=>{for(const value of [950,1050])assert.equal(purchaseAllocation({purchase_difference_mode:'accept',matched_purchase_allocated_amount:value,teslimOlanTonaj:1,alisFiyati:1000}),value);});
test('price refund is KDV-inclusive, targets supplier and identifies source invoice and sale',()=>{const result=refundPayload({id:'sale',purchase_difference_amount:50},{supplier_id:'supplier',purchase_bill_id:'source',invoice_no:'INV'},20,'2026-10-09').data;assert.equal(result.attributes.net_total,50);assert.equal(result.attributes.total_vat,8.33);assert.equal(result.attributes.item_type,'refund');assert.equal(result.relationships.supplier.data.id,'supplier');assert.match(result.attributes.description,/INV.*sale.*source/);assert.equal(refundPayload({id:'sale',purchase_difference_amount:50},{supplier_id:'supplier'},0,'2026-10-09').data.attributes.total_vat,0);});
test('refund rejects negative amounts, missing VAT and unsupported extra taxes',()=>{assert.throws(()=>refundPayload({purchase_difference_amount:-50},{},0,'date'));assert.throws(()=>refundVatRates({included:[{type:'purchase_bill_details',attributes:{}}]}));assert.throws(()=>refundVatRates({included:[{type:'purchase_bill_details',attributes:{vat_rate:20,vat_withholding_rate:50}}]}));const rates=refundVatRates({included:[0,20,20].map(vat_rate=>({type:'purchase_bill_details',attributes:{vat_rate}}))});assert.equal(JSON.stringify(rates),'[0,20]');});
function refundRoute({reserveError=null,confirm=true,sourceSupplier='supplier',state='pending',refundId=null,wrongCreatedTotal=false}={}){
 const calls=[];const order={id:'sale',purchase_difference_mode:'refund',purchase_difference_amount:50,purchase_difference_expected:1000,matched_purchase_invoice_id:'source',purchase_refund_state:state,purchase_refund_id:refundId};const bill={purchase_bill_id:'source',supplier_id:'supplier',total:1050,state:'ready'};
 const db={from:table=>{const query={select:()=>query,eq:()=>query,single:async()=>({data:table==='siparisler'?order:bill}),update:()=>({eq:async()=>({error:null})})};return query},rpc:async()=>({error:reserveError})};
 const mod={exports:{}};const ctx={module:mod,exports:mod.exports,Request,URLSearchParams,Intl,Date,process:{env:{PARASUT_COMPANY_ID:'company'}},require:name=>name.includes('purchase-refund')?{refundPayload,refundVatRates}:name.includes('invoice-pool')?{invoiceAdmin:()=>db}:name.includes('whatsapp')?{authorizeWhatsApp:async()=>null}:{NextResponse:{json:(data,init)=>({data,status:init?.status||200})}},fetch:async(url,options)=>{calls.push([url,options]);if(url.includes('oauth'))return{ok:true,json:async()=>({access_token:'demo'})};if(options?.method==='POST')return{ok:true,json:async()=>({data:{id:'refund'}})};return{ok:true,json:async()=>({data:{attributes:{net_total:url.includes('/refund?')?(wrongCreatedTotal?51:50):1050,total_vat:0,item_type:url.includes('/refund?')?'refund':'purchase_bill'},relationships:{supplier:{data:{id:sourceSupplier}}}},included:[{type:'purchase_bill_details',attributes:{vat_rate:0}}]})}}};vm.createContext(ctx);vm.runInContext(ts.transpile(fs.readFileSync('app/api/admin/parasut/purchase-refund/route.ts','utf8'),{module:ts.ModuleKind.CommonJS}),ctx);
 return{calls,post:()=>mod.exports.POST({json:async()=>({orderId:'sale',amount:50,vatRate:0,confirm})})};
}
test('refund handler creates once, verifies supplier and amount, and blocks reserved duplicates',async()=>{const f=refundRoute();assert.equal((await f.post()).data.success,true);assert.equal(f.calls.filter(([,options])=>options?.method==='POST' && !options.body?.get).length,1);const duplicate=refundRoute({reserveError:{message:'Önceki iade işlemi'}});assert.equal((await duplicate.post()).status,409);assert.equal(duplicate.calls.some(([url,options])=>url.includes('purchase_bills')&&options.method==='POST'),false);});
test('refund handler requires explicit confirmation and exact source supplier; unverified records cannot claim success',async()=>{for(const options of [{confirm:false},{sourceSupplier:'wrong'},{state:'created',refundId:'refund'},{wrongCreatedTotal:true}]){const f=refundRoute(options);assert.equal((await f.post()).status,409)}});
