"use client";
import { useEffect, useState } from 'react';
import { Pencil, Plus, Search, Trash2, UserRound } from 'lucide-react';
import { usePanelDialog } from '@/app/admin/ui/panel-dialog';
import { EditorDialog, EmptyState, Feedback, WhatsAppShell } from '../whatsapp-shell';
import base from '../gonder/send-page.module.css';
import styles from '../whatsapp-pages.module.css';
type Contact={id:string;name:string|null;phone:string;note:string|null};
export default function Page(){
  const [contacts,setContacts]=useState<Contact[]>([]),[search,setSearch]=useState(''),[message,setMessage]=useState('');
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(''),[page,setPage]=useState(1);
  const [editor,setEditor]=useState<Contact|'new'|null>(null),[name,setName]=useState(''),[phone,setPhone]=useState(''),[note,setNote]=useState(''),[editorError,setEditorError]=useState('');
  const {panelConfirm}=usePanelDialog();
  async function loadContacts(){setLoading(true);try{const res=await fetch('/api/admin/whatsapp/contacts',{cache:'no-store'});const data=await res.json();if(!res.ok || !data.success)throw new Error(data.error || 'Kişiler yüklenemedi.');setContacts(data.contacts || []);}catch(error){setMessage('❌ '+(error instanceof Error?error.message:'Kişiler yüklenemedi.'));}finally{setLoading(false);}}
  function openEditor(contact:Contact|'new'){setEditor(contact);setName(contact==='new'?'':contact.name || '');setPhone(contact==='new'?'':contact.phone.replace(/\D/g,''));setNote(contact==='new'?'':contact.note || '');setEditorError('');}
  async function save(){if(saving || !editor)return;if(!phone.trim()){setEditorError('❌ Telefon numarası zorunlu.');return;}setSaving(true);setEditorError('');try{const isNew=editor==='new';const res=await fetch(isNew?'/api/admin/whatsapp/contacts':`/api/admin/whatsapp/contacts/${encodeURIComponent(editor.id)}`,{method:isNew?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),phone:phone.replace(/\D/g,''),note:note.trim()})});const data=await res.json();if(!res.ok || !data.success)throw new Error(data.error || 'Kişi kaydedilemedi.');setEditor(null);setMessage(isNew?'✅ Kişi eklendi.':'✅ Kişi güncellendi.');await loadContacts();}catch(error){setEditorError('❌ '+(error instanceof Error?error.message:'Kişi kaydedilemedi.'));}finally{setSaving(false);}}
  async function deleteContact(contact:Contact){if(deleting || !await panelConfirm(`“${contact.name || contact.phone}” kişisini tamamen silmek istiyor musun?`))return;setDeleting(contact.id);try{const res=await fetch(`/api/admin/whatsapp/contacts/${encodeURIComponent(contact.id)}`,{method:'DELETE'});const data=await res.json();if(!res.ok || !data.success)throw new Error(data.error || 'Kişi silinemedi.');setMessage('✅ Kişi silindi.');await loadContacts();}catch(error){setMessage('❌ '+(error instanceof Error?error.message:'Kişi silinemedi.'));}finally{setDeleting('');}}
  useEffect(()=>{void loadContacts();},[]);
  const q=search.toLocaleLowerCase('tr-TR').trim();const filtered=contacts.filter(c=>[c.name,c.phone,c.note].filter(Boolean).join(' ').toLocaleLowerCase('tr-TR').includes(q));const pages=Math.max(1,Math.ceil(filtered.length/25));const currentPage=Math.min(page,pages);const visible=filtered.slice((currentPage-1)*25,currentPage*25);
  return <WhatsAppShell title="Kişiler" description="Müşteri ve bayi iletişim bilgilerini tek yerden yönet." active="contacts" onRefresh={loadContacts} loading={loading} action={<button type="button" className={base.primary} onClick={()=>openEditor('new')}><Plus size={17}/> Yeni kişi</button>}>
    <Feedback message={message}/><div className={styles.toolbar}><label className={styles.search}><Search size={17}/><span className="sr-only">Kişi ara</span><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}} placeholder="Ad, firma, telefon veya not ara…"/></label><span className={styles.hint}>{filtered.length} kişi</span></div>
    {visible.length ? <section className={styles.list} aria-label="Kişi listesi"><div className={styles.tableHead}><span>Ad / Firma</span><span>Telefon</span><span>Not</span><span>İşlem</span></div>{visible.map(c=><article key={c.id} className={styles.contactRow}><div className={styles.contactName}><span className={styles.avatar}>{c.name ? c.name.slice(0,1).toLocaleUpperCase('tr-TR') : <UserRound size={21}/>}</span><strong>{c.name || 'İsimsiz'}</strong></div><p className={styles.phone}>{c.phone}</p><p className={styles.note}>{c.note || 'Not eklenmedi'}</p><div className={styles.rowActions}><button type="button" className={styles.edit} onClick={()=>openEditor(c)} aria-label={`${c.name || c.phone} kişisini düzenle`}><Pencil size={14}/> Düzenle</button><button type="button" className={styles.danger} onClick={()=>deleteContact(c)} disabled={!!deleting} aria-label={`${c.name || c.phone} kişisini sil`}><Trash2 size={14}/>{deleting===c.id?'Siliniyor…':'Sil'}</button></div></article>)}</section> : <EmptyState loading={loading} filtered={!!search} label="Henüz kişi kaydı yok"/>}
    {pages>1 && <nav className={styles.pagination} aria-label="Kişi sayfaları"><span>{currentPage} / {pages} sayfa · {filtered.length} kişi</span><div><button type="button" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)} aria-label="Önceki sayfa">←</button><button type="button" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)} aria-label="Sonraki sayfa">→</button></div></nav>}
    {editor && <EditorDialog title={editor==='new'?'Yeni kişi ekle':'Kişiyi düzenle'} description="Telefon numarasını + işareti olmadan yaz. Örnek: 905xxxxxxxxx." onClose={()=>{if(!saving)setEditor(null);}}><form className={styles.dialogForm} onSubmit={event=>{event.preventDefault();void save();}}><label className={styles.field}><span>Ad / Firma</span><input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder="Müşteri veya firma adı" disabled={saving}/></label><label className={styles.field}><span>Telefon <span aria-hidden="true">*</span></span><input type="tel" inputMode="tel" autoComplete="tel" required value={phone} onChange={event=>setPhone(event.target.value.replace(/\D/g,''))} placeholder="905xxxxxxxxx" disabled={saving}/></label><label className={styles.field}><span>Not <small>(isteğe bağlı)</small></span><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Bölge, firma veya hatırlatma notu…" disabled={saving}/></label><Feedback message={editorError}/><div className={styles.dialogFooter}><button type="button" className={base.secondary} disabled={saving} onClick={()=>setEditor(null)}>Vazgeç</button><button type="submit" className={base.primary} disabled={saving || !phone.trim()}>{saving?'Kaydediliyor…':'Kaydet'}</button></div></form></EditorDialog>}
  </WhatsAppShell>;
}
